#include <stdlib.h>
#include <stdio.h>
#include <iostream>

using namespace std;

void default_fridge(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |    WELCOME USING    |            |" << std::endl;
    std::cout << "|          |    SMART FRIDGE     |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     //      //      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void check_food(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |   Check Food List   |            |" << std::endl;
    std::cout << "|          |  Please be patient  |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void check_done(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |   Check Food List   |            |" << std::endl;
    std::cout << "|          |       Done...       |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void grab_food(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |    Get your Food    |            |" << std::endl;
    std::cout << "|          |  Please be patient  |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void grab_done(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |    Get Your Food    |            |" << std::endl;
    std::cout << "|          |       Done...       |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void grab_fail(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |    Get Your Food    |            |" << std::endl;
    std::cout << "|          |      Failed...      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     --      --      |            |" << std::endl;
    std::cout << "|          |         /\\          |            |" << std::endl;
    std::cout << "|          |        /  \\         |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void order_food(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |      Order Food     |            |" << std::endl;
    std::cout << "|          | Contact with Grocery|            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void order_done(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |  Order from Grocery |            |" << std::endl;
    std::cout << "|          |       Done...       |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}

void off_fridge(){
    system("clear");
    std::cout << "-----------------------------------------------" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |  Ready to Shutdown  |            |" << std::endl;
    std::cout << "|          |       Byebye!       |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |     /\\      /\\      |            |" << std::endl;
    std::cout << "|          |                     |            |" << std::endl;
    std::cout << "|          |       ------        |            |" << std::endl;
    std::cout << "|          -----------------------            |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|                                             |" << std::endl;
    std::cout << "|---------------------------------------------|" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|           LSGN ©    SMART FRIDGE         |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "|                                          |  |" << std::endl;
    std::cout << "-----------------------------------------------" << std::endl;
}